// <auto-generated />
using System;
using FootballStats.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FootballStats.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FootballStats.Api.Models.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("FootballStats.Api.Models.RegistroPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assistencias")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("Gols")
                        .HasColumnType("integer");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.ToTable("RegistrosPartida", t =>
                        {
                            t.HasCheckConstraint("CK_RegistrosPartida_Assistencias", "\"Assistencias\" >= 0 AND \"Assistencias\" <= 99");

                            t.HasCheckConstraint("CK_RegistrosPartida_Gols", "\"Gols\" >= 0 AND \"Gols\" <= 99");
                        });
                });

            modelBuilder.Entity("FootballStats.Api.Models.RegistroPartida", b =>
                {
                    b.HasOne("FootballStats.Api.Models.Jogador", "Jogador")
                        .WithMany("Registros")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("FootballStats.Api.Models.Jogador", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
